spring.application.name=painting-service

spring.datasource.url=jdbc:mysql://localhost:3306/painting_store
spring.datasource.username=root
spring.datasource.password=Incorrect@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true